# Generated by Django 5.1.5 on 2025-05-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('capacidade', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reservaambiente',
            name='sala_reservada',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.sala'),
        ),
    ]
