# Generated by Django 5.1.5 on 2025-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usuario_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ni',
            field=models.CharField(default='', max_length=100, null=True, unique=True),
        ),
    ]
