# Generated by Django 5.1.5 on 2025-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usuario_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('D', 'Diretor'), ('P', 'Professor')], default='', max_length=100),
        ),
    ]
